/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as ProtectedLayoutImport } from "./routes/_protected/layout";
import { Route as AuthLayoutImport } from "./routes/_auth/layout";
import { Route as AuthIndexImport } from "./routes/_auth/index";
import { Route as ProtectedHomeImport } from "./routes/_protected/home";
import { Route as AuthRegisterImport } from "./routes/_auth/register";

// Create/Update Routes

const ProtectedLayoutRoute = ProtectedLayoutImport.update({
  id: "/_protected",
  getParentRoute: () => rootRoute,
} as any);

const AuthLayoutRoute = AuthLayoutImport.update({
  id: "/_auth",
  getParentRoute: () => rootRoute,
} as any);

const AuthIndexRoute = AuthIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthLayoutRoute,
} as any);

const ProtectedHomeRoute = ProtectedHomeImport.update({
  id: "/home",
  path: "/home",
  getParentRoute: () => ProtectedLayoutRoute,
} as any);

const AuthRegisterRoute = AuthRegisterImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => AuthLayoutRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthLayoutImport;
      parentRoute: typeof rootRoute;
    };
    "/_protected": {
      id: "/_protected";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof ProtectedLayoutImport;
      parentRoute: typeof rootRoute;
    };
    "/_auth/register": {
      id: "/_auth/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof AuthRegisterImport;
      parentRoute: typeof AuthLayoutImport;
    };
    "/_protected/home": {
      id: "/_protected/home";
      path: "/home";
      fullPath: "/home";
      preLoaderRoute: typeof ProtectedHomeImport;
      parentRoute: typeof ProtectedLayoutImport;
    };
    "/_auth/": {
      id: "/_auth/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AuthIndexImport;
      parentRoute: typeof AuthLayoutImport;
    };
  }
}

// Create and export the route tree

interface AuthLayoutRouteChildren {
  AuthRegisterRoute: typeof AuthRegisterRoute;
  AuthIndexRoute: typeof AuthIndexRoute;
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthRegisterRoute: AuthRegisterRoute,
  AuthIndexRoute: AuthIndexRoute,
};

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
);

interface ProtectedLayoutRouteChildren {
  ProtectedHomeRoute: typeof ProtectedHomeRoute;
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedHomeRoute: ProtectedHomeRoute,
};

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
);

export interface FileRoutesByFullPath {
  "": typeof ProtectedLayoutRouteWithChildren;
  "/register": typeof AuthRegisterRoute;
  "/home": typeof ProtectedHomeRoute;
  "/": typeof AuthIndexRoute;
}

export interface FileRoutesByTo {
  "": typeof ProtectedLayoutRouteWithChildren;
  "/register": typeof AuthRegisterRoute;
  "/home": typeof ProtectedHomeRoute;
  "/": typeof AuthIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/_auth": typeof AuthLayoutRouteWithChildren;
  "/_protected": typeof ProtectedLayoutRouteWithChildren;
  "/_auth/register": typeof AuthRegisterRoute;
  "/_protected/home": typeof ProtectedHomeRoute;
  "/_auth/": typeof AuthIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "" | "/register" | "/home" | "/";
  fileRoutesByTo: FileRoutesByTo;
  to: "" | "/register" | "/home" | "/";
  id:
    | "__root__"
    | "/_auth"
    | "/_protected"
    | "/_auth/register"
    | "/_protected/home"
    | "/_auth/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren;
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_protected"
      ]
    },
    "/_auth": {
      "filePath": "_auth/layout.tsx",
      "children": [
        "/_auth/register",
        "/_auth/"
      ]
    },
    "/_protected": {
      "filePath": "_protected/layout.tsx",
      "children": [
        "/_protected/home"
      ]
    },
    "/_auth/register": {
      "filePath": "_auth/register.tsx",
      "parent": "/_auth"
    },
    "/_protected/home": {
      "filePath": "_protected/home.tsx",
      "parent": "/_protected"
    },
    "/_auth/": {
      "filePath": "_auth/index.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
