#!/bin/sh
cd ./app

# Folder check
FOLDER_PATH="./node_modules"

if [ ! -d "$FOLDER_PATH" ]; then
	echo "husky is not installed, skipping precommit hooks (not an error)..."
else
	echo "Running precommit hooks..."
	# run prettier + linter
	npx lint-staged
fi

